### ISSUE TITLE
Pidgin crash after new Whatsapp status

### ISSUE THREAD

**Issue by rvdborgt** [hoehermann/purple-gowhatsapp#141]
When Pidgin starts and someone has posted a new status in Whatsapp, then Pidgin's message window opens for a few seconds, freezes (with the mouse cursor spinning) and then Pidgin crashes. Starting Pidgin again is fine after that.
I don't know (yet) what happens when someone posts a new status message while Pidgin is running; it doesn't happen very often, only once per week or so. Normal Whatsapp messages work fine.

This is on Windows 11 with Pidgin 2.14.10 and the Whatsmeow build from 3 December. I see there's a new build from 11/12, so I'll try that, but previous new builds didn't help either.
Is there any info (logs etc.) I should collect when it happens again?

**Comment by hoehermann** [comment]
Thank you for the report. Please be aware that recent build may crash frequently. I have not had the time to look at it. See #138.

I hope I can look into this issue this year. My contacts do not use statuses. Since I only have one phone, I cannot observe a contact's status update myself. For these reasons, any information you can provide to me may be useful.

You can check your ["purple" directory](https://developer.pidgin.im/wiki/Using%20Pidgin#Whereismy.purpledirectory) for a .rpt file.

Additionally, you can start Pidgin from the command-line (PowerShell or cmd makes no difference) with verbose debug output enabled: `pidgin.exe -d > C:\Users\username\Desktop\pidgin.log`

Since they can contain sensitive information, you probably want to send me the files via mail instead of github: github@hehoe.de

**Comment by rvdborgt** [comment]
Pidgin closed by itself yesterday evening and that was after someone had posted a Whatsapp status so I guess that also makes a running Pidgin crash.
My pidgin.rpt is over 2 years old. It goes all the way back to 2012 but then suddenly stops in June 2020. But I've now started Pidgin with verbose output. Maybe I'll ask a friend to post a status to see what happens and I'll then mail the log file.

**Comment by rvdborgt** [comment]
It just happened again, with a status update containing only images. I sent the log, I hope it helps.

**Comment by hoehermann** [comment]
Thank you for the log. I looked into it and can see that the crash happens after the message was received.

Unfortunately, I am unable to replicate the crash for further investigation. In fact, I fail to send a status update at all. Since I do not have a second phone, I went through the process of setting up a virtual android device. I can send status updates, but I never received them on my main phone. Consequently, I cannot receive them on the plug-in, either. I tried until WhatsApp servers decided I was sending out too many status updates.

Maybe I will look into this again another day. For now, I put this on the list of known issues. In the plug-in, status updates are now ignored by default.

**Comment by rvdborgt** [comment]
I enabled status broadcasts again after reading [this comment](https://github.com/hoehermann/purple-gowhatsapp/issues/147#issuecomment-1371693874) and I received a status message without a Pidgin crash. So this issue may have been solved automagically.
