### ISSUE TITLE
Error reading from websocket

### ISSUE THREAD

**Issue by Industry** [hoehermann/purple-gowhatsapp#153]
I am consistently getting this error and requiring to reconnect. Any way to debug and determine what's causing it?
`[Client/Socket] Error reading from websocket: websocket: close 1006 (abnormal closure): unexpected EO`

**Comment by hoehermann** [comment]
Unfortunately, there is nothing I can do about this. Basic connectivity issues aside, this means WhatsApp servers do not like your device in particular. Also see [related issues at whatsmeow](https://github.com/tulir/whatsmeow/issues?q=is%3Aissue+Error+reading+from+websocket).

**Comment by Industry** [comment]
I would be happy to change the device to avoid the issue. I am running Pidgin 2.14.12 (libpurple 2.14.12) (the portable version) on Windows 11 x64 and whatsmeow nightly build 2023-02-23. Perhaps there's a more compatible Windows version?

**Comment by hoehermann** [comment]
Sorry, I do not know why WhatsApp servers reject your connection attempts. In fact, I daresay no-one in the community knows for sure. There is some speculation [here](https://github.com/tulir/whatsmeow/issues/14#issuecomment-1339636951) and [there](https://github.com/tulir/whatsmeow/issues/28#issuecomment-1336364364), but nothing definitive.

**Comment by heeplr** [comment]
I'm experiencing this aswell. Is whatsmeow somehow transferring the client IP adress to whatsapp?

I'm using spectrum2 + Conversations and the issue seems to come up, when Conversations changes from WIFI to mobile connection. Not always, but sometimes. (In theory, whatsapp should only see the spectrum2 server but maybe it's somehow related anyway...?) 

Just a wild guess.

EDIT: ```bridge-compatibility=true``` is set.
