### ISSUE TITLE
Research PTT Flag

### ISSUE THREAD

**Issue by hoehermann** [hoehermann/purple-gowhatsapp#168]
Do I want to use it for voice messages?

**Comment by beadon** [comment]
Push To Talk -- a very neat addition, however it could be complex to manage a lot of these messages.I suspect this is lightly used.

However, it is called out in a few articles as a deficiency of Pidgin.  Is this somethign supported natively within the Pidgin interface ?

The comparison is made here for PTT , WeChat vs Pidgin :
https://www.slant.co/versus/1927/4381/~wechat_vs_pidgin

**Comment by hoehermann** [comment]
As far as it was described to me, "Push To Talk" is just a WhatsApp brand name for "voice message". I have not looked into it in detail.

This is not the "voice call" feature. That is as far as I know not supported by the WhatsApp Web API hence I cannot add it to this plug-in.

**Comment by deuill** [comment]
Since I'm driving through: `Ptt: true` is meant to denote voice messages, which offer slightly different UX in official clients (back-to-back voice messages play as one continuous message, there's waveform displays, etc.), but come with their own set of requirements:

  - MIME type (and corresponding file contents) must be in `audio/ogg; codecs=opus`  format.
  - Duration set in `Seconds` appears to be mandatory.
  - `Waveform` also appears to be mandatory, though I've seen Android and iOS clients render voice messages correctly even with no waveform attached.

There's some implementation [here](https://git.sr.ht/~nicoco/slidge-whatsapp/tree/8b6fc9478017f832b6d77dd8ccb36d3ad9c3c387/item/slidge_whatsapp/event.go#L425-427), with waveform bits [here](https://git.sr.ht/~nicoco/slidge-whatsapp/tree/8b6fc9478017f832b6d77dd8ccb36d3ad9c3c387/item/slidge_whatsapp/media.go#L323-365) and some additional context/discussion [here](https://github.com/tulir/whatsmeow/discussions/432).

The distinction between `Ptt: true` and `Ptt: false` can be seen in official clients by sending a voice message vs. sending an audio message -- the latter presents slightly different UX, but is eminently workable either way.

**Comment by hoehermann** [comment]
Thank you for your contribution @deuill. Thanks to your information, I was able to add the feature to the plug-in. Well, almost. I am currently stricken with a case of stupidity and cannot get the waveform to look right.

**Comment by beadon** [comment]
@hoehermann which IRC channel ?  Or whatsapp(?) channel are you in, let's collab !  direct message ..

**Comment by hoehermann** [comment]
Got it. I stumbled over C being C. Calling `abs()` instead of `fabs()` on a smallish float will dutifully return zero. 🤦 A true classic.

The waveform is not perfectly accurate, but close enough by my standards.

@beadon Thank you for the offer. 🙂 This one I wanted to find on my own. I will probably get back to you on another occasion.
