### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by beadon** [hoehermann/purple-gowhatsapp#173]
As part of the packaging process I need to include notes indicating the changes since the last version update.  Referring to the releases page on github, this information is not present.

Where should I construct release notes from ?

Also, I propose release notes stored in a brief summary format, including "known issues" in the release section of this repository.

**Comment by hoehermann** [comment]
This has been requested in the past. Ever since that, changes are documented in a condensed fashion in [CHANGELOG.md](https://github.com/hoehermann/purple-gowhatsapp/blob/whatsmeow/CHANGELOG.md) and also redundantly in the description of the tagged commit, see [this example](https://github.com/hoehermann/purple-gowhatsapp/releases/tag/v1.12.0).

**Comment by beadon** [comment]
Got it. Ok, I can use CHANGELOG if this is the de-factor place for change notes.  This will inform packaging notes as I need to fit this into DEB style for the wider Debian APT packaging system.  Thank you for identifying where the notes are typically stored.

If we explore releases auto-uploaded to github (gh) , then bumping the version and this CHANGELOG when there's an auto-rebuild and inclusion of a dependency will come into play.

The reason it came up for me here was the commit message - I wasn't expecting branch tags to have release notes.  So, it was non-intuitive (for me) to examine the tag for a changelog.  I imagine others raised the request for similar reasons.
