### ISSUE TITLE
Nightly Build unavailable since host hehoe.de is down

### ISSUE THREAD

**Issue by ALDamico** [hoehermann/purple-gowhatsapp#182]
It appears that the link to the nightly builds timeouts every time, making it impossible to download them.

**Comment by hoehermann** [comment]
Thank you for the report. Indeed, hehoe.de has IPv4 connectivity issues. It is accessible via IPv6, though. The server's configuration has not changed. I am afraid, the data centre's provider needs to take a look at it. Since I do not want to pay for the premium support, there is nothing I can do during the holidays.

**Update:** The issue has been resolved by the provider.
