### ISSUE TITLE
Trying to join a group with JID="status@broadcast" makes pidgin hang

### ISSUE THREAD

**Issue by Juliaria08** [hoehermann/purple-gowhatsapp#195]
The title is self explanatory.
I wanted to try to join the special group, but I couldn't from the join a chat menu.
I typed in:
```
JID: status@broadcast
Name: status
```

And pidgin hangs, (and to kill it I have to send it another signal different from SIGTERM for it to stop)

Thanks in advance.

**Comment by hoehermann** [comment]
Thank you for your message. I think `status@broadcast` technically is a contact, not a group. The plug-in is calling [Client.GetGroupInfo](https://pkg.go.dev/go.mau.fi/whatsmeow#Client.GetGroupInfo), which does take a long time to timeout when fed with invalid data.

Apart from that, I have to tell you I never could get status broadcasts to work. Or any other of the special servers known to [jid.go](https://github.com/tulir/whatsmeow/blob/main/types/jid.go):

	LegacyUserServer  = "c.us"
	BroadcastServer   = "broadcast"
	HiddenUserServer  = "lid"
	MessengerServer   = "msgr"
	InteropServer     = "interop"
	NewsletterServer  = "newsletter"
	HostedServer      = "hosted"

In case of the broadcast server: For some users it works, for some it does not. It was working for me for some time, then it stopped working and receiving messages from it produced crashes. Since my actual contacts do not use broadcasts at all and I fail to generate broadcasts in my test environment, I have a hard time developing support for these servers. I am sorry, but I cannot add features involving the broadcast server. Contributions are welcome. 🙂

That said, I consider only the default (single contact conversation) and group chat server to be supported:

	DefaultUserServer = "s.whatsapp.net"
	GroupServer       = "g.us"

**Comment by Juliaria08** [comment]
Ah, ok.

**Comment by Juliaria08** [comment]
(they are working for me when one of my contacts sends a broadcast)

**Comment by hoehermann** [comment]
I just noticed that https://pkg.go.dev/go.mau.fi/whatsmeow#section-readme states:

> Things that are not yet implemented: Sending broadcast list messages (this is not supported on WhatsApp web either)

Since receiving works, I consider the temporary UI lock-up upon trying to join a non-existent group a minor issue.

**Comment by Juliaria08** [comment]
Ok, then I'll close.
