### ISSUE TITLE
Pairing phone with a 8-letter code

### ISSUE THREAD

**Issue by ReinJG** [hoehermann/purple-gowhatsapp#204]
Could the functionality of pairing a phone with a 8-letter code instead of a QR code be added?

This is implemented in for example [mautrix/whatsapp](https://github.com/mautrix/whatsapp) by using the method [Client.PairPhone](https://pkg.go.dev/go.mau.fi/whatsmeow#Client.PairPhone) from the whatsmeow library.

**Comment by hoehermann** [comment]
Thank you for the suggestion. It is very reasonable. I did not even know of this feature. No estimate when I want to do it, though.

**Comment by hoehermann** [comment]
Implemented in 21b78e6. I added extra detailed descriptions when used with terminal-based clients. I hope it helps. Feed-back is welcome. Since this will affect protocol bridges more than Pidgin users, I hope that some folks can run tests in their set-ups. @mverboom @mooomooo @demure @Strykar @yourealwaysbe @quotuva @evgenyh @heeplr or @msebald maybe?

**Comment by yourealwaysbe** [comment]
Awesome! -- i run WhatsApp on an old phone whose camera struggles with QR codes. The 8 letter code is much more convenient and doesn't require WeeChat plugins to render.

The first code didn't work for me and i had to reconnect to get a new one. I assume the codes timeout like the QR codes and i was too slow. Maybe it's worth adding a remark to the "Please enter..." message to avoid surprised users?
