### ISSUE TITLE
not all contacts appear with aliases in Pidgin

### ISSUE THREAD

**Issue by Geremia** [hoehermann/purple-gowhatsapp#75]
I have "Fetch contact list from phone on connect" checked, but only some of my contacts appear with aliases in Pidgin, despite all of them having associated names in my phone's contact list and my phone's WhatsApp. Is there a way for it to re-fetch aliases from the phone?

I'm built the latest master of libgowhatsapp.so.

**Comment by hoehermann** [comment]
The alias is set only once when the buddy is added.

This is intentional as I want "Steve" to always appear as "Steve from Work" and not as "Steve – I now have a new car" or whatever they may change their details to. I can add a "update local buddy on remote change" feature, though.

For now, you can delete the offending contact from Pidgin's buddy list (this is a local change only). Next time you connect, the contact is re-added with their current data.

**Comment by EionRobb** [comment]
if it helps, libpurple has different types of alias.  There's a "server alias" which is the name/details that the server provides, eg "Steve has a car", and the "local alias" which is the "Steve from Work".  When displaying, the local alias has higher priority.  Normally the UI would be in control of setting the local alias and not the prpl, but for keeping local aliases in sync, prpl's can set the local alias too.  The server alias is set via serv_got_alias() and the local one set with the purple_buddy_set_alias()

**Comment by Geremia** [comment]
I fixed the issue by deleting the WhatsApp group (and thus all my WhatsApp contacts) in my Pidgin contact list, disabling, and re-enabling the "WhatsApp (HTTP)" account. It re-read all my contacts because I had "Fetch contact list from phone on connect" checked.
